### ISSUE TITLE
False: Fly Hack Vines

### ISSUE THREAD

**Issue by steviebeenz** [steviebeenz/NOPE#19]
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_
Paper @ Latest (auto update) 
**What Minecraft Client Version are you running?**
1.15 Sigma 
**What version of NOPE are you running?**
_You can find this out by running /nope ingame_
Steviebeenz's Fork
**What is the debug ID?**
_You can find this out by typing /nope toggle dev to enable dev mode, it should look something like HackName#Number_
Speed#1
**Is there any debug information? (Please include average info if available)**
_You can see if there's any by hovering over the [DEV] message_

**What is causing this false positive?**
_What exactly are you doing that causes a false positive?_
Fly Hacking up vines triggers speed
**Is this false positive reproducible on the test server?**
_MSWS.xyz is the IP_
No
**Please list all your server plugins**
Nope
**Is there anything else to add?**
Use my fork it's better.

**Comment by tkn0** [comment]
I mean at least it flags you

**Comment by steviebeenz** [comment]
@tkn0 this was a webhook test ;D
